spring.application.name=Vote

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/Election
spring.datasource.username=root
spring.datasource.password=shishu@7667893292

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
